const CLUBS=['Driver','3W','5i','6i','7i','8i','9i','PW','AW','52°','56°','60°','Putter'];
const seedCourses=[
 {id:'best',name:'Best Golf & Country Club',location:'Best',favorite:true,tees:[
  {id:'yellow',name:'Geel',holes:[339,356,106,363,377,156,317,488,277,478,332,193,434,392,476,309,156,342]},
  {id:'white',name:'Wit',holes:[343,380,106,372,390,158,317,528,281,481,336,211,434,410,479,312,164,347]},
  {id:'blue',name:'Blauw',holes:[276,325,105,312,328,151,304,401,270,404,290,168,410,328,412,275,152,276]},
  {id:'red',name:'Rood',holes:[276,318,105,307,316,137,295,389,255,397,290,161,410,328,403,275,138,276]}
 ],pars:[4,4,3,4,4,3,4,5,4,5,4,3,5,4,5,4,3,4]},
 {id:'woold',name:'Golfbaan Het Woold',location:'Asten-Heusden',favorite:true,tees:[
  {id:'yellow',name:'Geel',holes:[320,365,480,355,163,325,343,138,465,375,310,495,355,130,307,280,138,490]},
  {id:'red',name:'Rood',holes:[270,305,413,310,144,285,285,110,405,320,255,420,320,110,262,230,114,420]},
  {id:'orange',name:'Oranje',holes:[243,274,371,278,105,0,0,0,0,0,0,0,0,0,0,0,0,0]}
 ],pars:[4,4,5,4,3,4,4,3,5,4,4,5,4,3,4,4,3,5]},
 {id:'vught',name:'Golfclub Vught',location:'Vught',favorite:true,tees:[
  {id:'standard',name:'Standaard',holes:[121,109,64,67,125,68,100,76,107]}
 ],pars:[3,3,3,3,3,3,3,3,3]},
];
const store={
 get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},
 set(k,v){localStorage.setItem(k,JSON.stringify(v))}
};
let state={tab:'home',courses:store.get('golf_courses',seedCourses),rounds:store.get('golf_rounds',[]),bag:store.get('golf_bag',CLUBS),activeRoundId:store.get('golf_active_round',null),modal:null};
let shotDraft={club:null,result:null,distance:''};
let gps={enabled:false,watchId:null,pos:null,error:null,updatedAt:null};
let golfMap=null;
function save(){store.set('golf_courses',state.courses);store.set('golf_rounds',state.rounds);store.set('golf_bag',state.bag);store.set('golf_active_round',state.activeRoundId)}
function activeRound(){return state.rounds.find(r=>r.id===state.activeRoundId)}
function courseFor(r){return state.courses.find(c=>c.id===r.courseId)}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1700)}

function haversineMeters(a,b){
 if(!a||!b)return null;const R=6371000,toRad=d=>d*Math.PI/180;
 const dLat=toRad(b.lat-a.lat),dLon=toRad(b.lng-a.lng),lat1=toRad(a.lat),lat2=toRad(b.lat);
 const h=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLon/2)**2;
 return Math.round(2*R*Math.asin(Math.sqrt(h)));
}
function gpsPoint(){return gps.pos?{lat:gps.pos.lat,lng:gps.pos.lng,accuracy:Math.round(gps.pos.accuracy||0),at:new Date().toISOString()}:null}
function startGPS(){
 if(!navigator.geolocation){gps.error='GPS wordt niet ondersteund op dit toestel.';render();return}
 if(gps.watchId!==null)return;
 gps.enabled=true;gps.error=null;render();
 gps.watchId=navigator.geolocation.watchPosition(p=>{
   gps.pos={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy};gps.updatedAt=Date.now();gps.error=null;updateMapLive();updateGpsText();
 },e=>{gps.error=e.code===1?'Locatietoegang is geweigerd. Sta locatie toe voor deze site.':'GPS-positie kon niet worden bepaald.';gps.enabled=false;if(gps.watchId!==null){navigator.geolocation.clearWatch(gps.watchId);gps.watchId=null}render()},
 {enableHighAccuracy:true,maximumAge:3000,timeout:12000});
}
function stopGPS(){if(gps.watchId!==null&&navigator.geolocation)navigator.geolocation.clearWatch(gps.watchId);gps.watchId=null;gps.enabled=false;gps.error=null;render()}
function updateGpsText(){const el=document.getElementById('gpsStatus');if(!el)return;if(gps.pos)el.textContent=`GPS ±${Math.round(gps.pos.accuracy||0)} m`;else el.textContent=gps.enabled?'GPS zoeken…':'GPS uit'}
function initRoundMap(){
 const el=document.getElementById('golfMap');if(!el||!window.L)return;
 if(golfMap){try{golfMap.remove()}catch{}golfMap=null}
 const r=activeRound(),shots=r?getHoleShots(r,r.currentHole):[];
 let center=gps.pos?[gps.pos.lat,gps.pos.lng]:shots.find(s=>s.gps)?.gps?[shots.find(s=>s.gps).gps.lat,shots.find(s=>s.gps).gps.lng]:[51.75,5.35];
 golfMap=L.map(el,{zoomControl:true,attributionControl:true}).setView(center,gps.pos?17:9);
 L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'&copy; OpenStreetMap contributors'}).addTo(golfMap);
 const pts=[];
 shots.filter(s=>s.gps).forEach(s=>{const ll=[s.gps.lat,s.gps.lng];pts.push(ll);L.circleMarker(ll,{radius:7,weight:2,fillOpacity:.85}).addTo(golfMap).bindTooltip(`${s.seq}. ${s.club}${s.distance?` · ${s.distance} m`:''}`)});
 if(pts.length>1)L.polyline(pts,{weight:3,opacity:.7}).addTo(golfMap);
 updateMapLive();
 setTimeout(()=>{try{golfMap.invalidateSize()}catch{}},80);
}
function updateMapLive(){
 if(!golfMap||!gps.pos||!window.L)return;
 if(golfMap._gpsMarker){golfMap._gpsMarker.setLatLng([gps.pos.lat,gps.pos.lng]);golfMap._gpsAccuracy.setLatLng([gps.pos.lat,gps.pos.lng]).setRadius(gps.pos.accuracy||0)}
 else{golfMap._gpsAccuracy=L.circle([gps.pos.lat,gps.pos.lng],{radius:gps.pos.accuracy||0,weight:1,fillOpacity:.08}).addTo(golfMap);golfMap._gpsMarker=L.circleMarker([gps.pos.lat,gps.pos.lng],{radius:8,weight:3,fillOpacity:1}).addTo(golfMap).bindTooltip('Jij bent hier')}
}
function centerOnGPS(){if(!gps.pos){startGPS();return}if(golfMap)golfMap.setView([gps.pos.lat,gps.pos.lng],18)}

function scoreLabel(score,par){if(score===0)return '–';const d=score-par;return d===0?'E':d>0?`+${d}`:`${d}`}
function roundScore(r){const c=courseFor(r);let score=0,par=0;for(let i=0;i<r.holesCount;i++){let s=r.shots.filter(x=>x.hole===i+1).reduce((a,x)=>a+1+(x.penalty||0),0);if(s){score+=s;par+=c.pars[i]}}return {score,par,diff:score&&par?score-par:0}}
function getHoleShots(r,n){return r.shots.filter(s=>s.hole===n).sort((a,b)=>a.seq-b.seq)}
function derived(r){let total=0,putts=0,pen=0,firHit=0,firOpp=0,girHit=0,girOpp=0,missL=0,missR=0,missS=0,missLong=0;
 const c=courseFor(r);for(let h=1;h<=r.holesCount;h++){const shots=getHoleShots(r,h);if(!shots.length)continue;total+=shots.length;shots.forEach(s=>{if(s.club==='Putter')putts++;pen+=s.penalty||0;if(s.result==='Links')missL++;if(s.result==='Rechts')missR++;if(s.result==='Kort')missS++;if(s.result==='Lang')missLong++});if(c.pars[h-1]>3){firOpp++;if(['Fairway','Doel'].includes(shots[0]?.result))firHit++}girOpp++;const girThreshold=c.pars[h-1]-2;const greenIndex=shots.findIndex(s=>['Green','Hole'].includes(s.result));if(greenIndex>=0&&greenIndex+1<=girThreshold)girHit++}
 return{total,putts,pen,fir:firOpp?Math.round(firHit/firOpp*100):0,gir:girOpp?Math.round(girHit/girOpp*100):0,missL,missR,missS,missLong}}
function nav(){return `<nav class="bottom-nav">${[['home','⌂','Home'],['round','⛳','Ronde'],['analysis','▥','Analyse'],['clubs','◒','Clubs'],['game','◎','Mijn spel']].map(([id,ic,tx])=>`<button class="nav-btn ${state.tab===id?'active':''}" data-tab="${id}"><b>${ic}</b>${tx}</button>`).join('')}</nav>`}
function shell(title,body,eyebrow='MIJN GOLF'){return `<div class="app-shell"><header class="topbar"><div class="eyebrow">${eyebrow}</div><h1>${title}</h1></header><main class="page">${body}</main>${nav()}</div>${state.modal?renderModal():''}`}
function home(){const r=activeRound();const done=state.rounds.filter(x=>x.completed);const last=done.at(-1);let body='';if(r){const sc=roundScore(r);body+=`<div class="card round-banner"><div><span class="eyebrow">LOPENDE RONDE</span><strong>${esc(courseFor(r).name)}</strong><span class="muted tiny">Hole ${r.currentHole} · ${scoreLabel(sc.score,sc.par)}</span></div><button class="btn btn-primary" data-tab="round">Verder</button></div>`}body+=`<section class="hero"><div class="eyebrow" style="color:#bcd6cb">SNEL OP DE BAAN</div><h2>Registreer elke slag zonder gedoe.</h2><p>Club kiezen, resultaat tikken, klaar. De rest rekent de app voor je uit.</p><button class="btn btn-primary" data-action="new-round">Nieuwe ronde</button></section>`;
 body+=`<div class="stat-row"><div class="stat"><strong>${done.length}</strong><span>rondes</span></div><div class="stat"><strong>${last?roundScore(last).score:'–'}</strong><span>laatste score</span></div><div class="stat"><strong>${last?derived(last).putts:'–'}</strong><span>laatste putts</span></div></div><div class="section-title"><h3>Favoriete banen</h3><button class="linkbtn" data-action="courses">Alle banen</button></div>${state.courses.filter(c=>c.favorite).map(courseCard).join('')}`;
 return shell('Dashboard',body)}
function courseCard(c){return `<button class="card course" style="width:100%;text-align:left;border:0" data-action="pick-course" data-id="${c.id}"><div class="course-icon">⛳</div><div class="course-main"><h4>${esc(c.name)}</h4><p>${esc(c.location)} · ${c.pars.length} holes · par ${c.pars.reduce((a,b)=>a+b,0)}</p></div><span class="chev">›</span></button>`}
function roundPage(){const r=activeRound();if(!r)return shell('Ronde',`<div class="empty"><h3>Nog geen ronde bezig</h3><p>Start een ronde en dit wordt je hoofdscherm tijdens het spelen.</p><button class="btn btn-primary" data-action="new-round">Nieuwe ronde starten</button></div>`);
 const c=courseFor(r),h=r.currentHole,shots=getHoleShots(r,h),par=c.pars[h-1],tee=c.tees.find(t=>t.id===r.teeId)||c.tees[0],len=tee.holes[h-1]||0,score=shots.reduce((a,x)=>a+1+(x.penalty||0),0); const scoreTxt=scoreLabel(score,par);
 const clubs=suggestedClubs(shots,par).map(x=>`<button class="club ${x.suggested?'suggested':''} ${shotDraft.club===x.name?'selected':''}" data-club="${esc(x.name)}">${esc(x.name)}</button>`).join('');
 const results=resultOptions(shots).map(x=>`<button class="result ${shotDraft.result===x?'selected':''}" data-result="${x}">${x}</button>`).join('');
 let body=`<div class="hole-head"><div class="hole-kicker"><span>Hole ${h} van ${r.holesCount}</span><span>${len?len+' m':''}</span></div><div class="hole-title"><h2>Par ${par}</h2><div class="hole-score"><strong>${scoreTxt}</strong><span>${score} slag${score===1?'':'en'}</span></div></div></div>`;
 body+=`<div class="card map-card"><div class="map-toolbar"><div><strong>Baan & GPS</strong><div id="gpsStatus" class="tiny muted">${gps.pos?`GPS ±${Math.round(gps.pos.accuracy||0)} m`:gps.enabled?'GPS zoeken…':'GPS uit'}</div></div><div class="map-actions"><button class="btn btn-ghost btn-small" data-action="center-gps">⌖</button><button class="btn ${gps.enabled?'btn-danger':'btn-secondary'} btn-small" data-action="toggle-gps">${gps.enabled?'GPS uit':'GPS aan'}</button></div></div><div id="golfMap" class="golf-map"></div>${gps.error?`<div class="gps-error">${esc(gps.error)}</div>`:''}<div class="tiny muted map-note">GPS-posities worden alleen lokaal in deze ronde bewaard. Bij je volgende slag kan de afstand van de vorige slag automatisch worden berekend.</div></div>`;
 body+=`<div class="hole-tabs">${Array.from({length:r.holesCount},(_,i)=>`<button class="hole-tab ${h===i+1?'active':''} ${getHoleShots(r,i+1).length?'done':''}" data-hole="${i+1}">${i+1}</button>`).join('')}</div>`;
 body+=`<div class="card shot-panel"><div class="shot-step-title"><h3 style="margin:0">${shots.length+1}e slag</h3><span class="badge">2 tikken</span></div><div class="eyebrow" style="margin-bottom:7px">1 · CLUB</div><div class="club-grid">${clubs}</div><div class="eyebrow" style="margin:16px 0 7px">2 · RESULTAAT</div><div class="result-grid">${results}</div><button class="linkbtn" style="margin-top:14px" data-action="details">+ extra details</button><div class="quick-save"><button class="btn btn-primary" data-action="save-shot" ${!shotDraft.club||!shotDraft.result?'disabled':''}>Slag opslaan</button></div></div>`;
 body+=`<div class="section-title"><h3>Slagen hole ${h}</h3><span class="muted">${score||0}</span></div><div class="card shot-list">${shots.length?shots.map(s=>shotItem(s)).join(''):'<div class="empty">Nog geen slagen geregistreerd.</div>'}</div>`;
 body+=`<div class="grid2"><button class="btn btn-ghost" data-action="prev-hole" ${h===1?'disabled':''}>← Vorige</button><button class="btn btn-secondary" data-action="next-hole">${h===r.holesCount?'Ronde afronden':'Volgende hole →'}</button></div>`;
 return shell(`${esc(c.name)}`,body,'RONDE')}
function suggestedClubs(shots,par){let priority;if(shots.length===0)priority=par===3?['7i','8i','9i','6i','PW','5i']:['Driver','3W','5i','6i'];else if(shots.at(-1)?.result==='Green'||shots.at(-1)?.club==='Putter')priority=['Putter','56°','60°','52°'];else priority=['7i','8i','6i','9i','5i','PW','AW','52°','56°','3W'];const arr=[...priority,...state.bag.filter(x=>!priority.includes(x))].filter(x=>state.bag.includes(x));return arr.map((n,i)=>({name:n,suggested:i<4}))}
function resultOptions(shots){if(shotDraft.club==='Putter'||shots.at(-1)?.result==='Green')return ['Hole','Kort','Lang','Links','Rechts','Doel'];if(shots.length===0)return ['Fairway','Links','Rechts','Green','Kort','Penalty'];return ['Green','Doel','Links','Rechts','Kort','Lang','Bunker','Penalty','Hole']}
function shotItem(s){return `<div class="shot-item"><div class="shot-num">${s.seq}</div><strong>${esc(s.club)}</strong><div><span>${esc(s.result)}</span>${s.distance?`<div class="tiny muted">${s.distance} m${s.distanceAuto?' · GPS':''}</div>`:''}${s.gps?`<div class="tiny muted">positie ±${s.gps.accuracy||'?'} m</div>`:''}</div><div class="shot-actions"><button title="Verwijderen" data-delete-shot="${s.id}">×</button></div></div>`}
function analysis(){const rounds=state.rounds.filter(r=>r.completed);if(!rounds.length)return shell('Analyse',`<div class="empty"><h3>Nog geen analyse</h3><p>Na je eerste afgeronde ronde verschijnen hier automatisch je patronen.</p></div>`,'PRESTATIES');const d=rounds.map(derived);const sum=k=>d.reduce((a,x)=>a+x[k],0);const avg=k=>Math.round(sum(k)/d.length);const body=`<div class="card"><div class="section-title" style="margin-top:0"><h3>Laatste ${Math.min(rounds.length,10)} rondes</h3></div><div class="stat-row"><div class="stat"><strong>${avg('fir')}%</strong><span>FIR</span></div><div class="stat"><strong>${avg('gir')}%</strong><span>GIR</span></div><div class="stat"><strong>${avg('putts')}</strong><span>putts/ronde</span></div></div></div>${metricBar('Miss links',sum('missL'),sum('missL')+sum('missR')+sum('missS')+sum('missLong'))}${metricBar('Miss rechts',sum('missR'),sum('missL')+sum('missR')+sum('missS')+sum('missLong'))}${metricBar('Kort',sum('missS'),sum('missL')+sum('missR')+sum('missS')+sum('missLong'))}${metricBar('Lang',sum('missLong'),sum('missL')+sum('missR')+sum('missS')+sum('missLong'))}<div class="card"><h3>Trainingsfocus</h3><p class="muted">${trainingFocus(rounds)}</p></div>`;return shell('Analyse',body,'PRESTATIES')}
function metricBar(label,val,total){const p=total?Math.round(val/total*100):0;return `<div class="card"><div class="analysis-line"><strong>${label}</strong><div class="bar"><i style="width:${p}%"></i></div><span class="right">${p}%</span></div></div>`}
function trainingFocus(rounds){const d=rounds.map(derived),S=k=>d.reduce((a,x)=>a+x[k],0);const misses=[['links',S('missL')],['rechts',S('missR')],['kort',S('missS')],['lang',S('missLong')]].sort((a,b)=>b[1]-a[1]);if(S('pen')>rounds.length*2)return 'Je verliest relatief veel slagen aan penalties. Focus eerst op veilige targets en tee-shots in het spel houden.';if(misses[0][1])return `Je meest voorkomende miss is ${misses[0][0]}. Dat patroon is nu het duidelijkste aangrijpingspunt voor je training.`;return 'Speel nog een paar rondes; daarna kan de app een duidelijker patroon herkennen.'}
function clubsPage(){const rounds=state.rounds;const rows=state.bag.map(c=>{const shots=rounds.flatMap(r=>r.shots).filter(s=>s.club===c);const d=shots.map(s=>Number(s.distance)).filter(Boolean);const avg=d.length?Math.round(d.reduce((a,b)=>a+b,0)/d.length):'–';return `<div class="card row"><div class="grow"><strong>${esc(c)}</strong><div class="tiny muted">${shots.length} slagen geregistreerd</div></div><div class="right"><strong>${avg}${avg==='–'?'':' m'}</strong><div class="tiny muted">gem. afstand</div></div></div>`}).join('');return shell('Clubs',rows+`<button class="fab" data-action="edit-bag">+</button>`,'MIJN BAG')}
function gamePage(){const rounds=state.rounds.filter(r=>r.completed);const cards=rounds.slice().reverse().map(r=>{const c=courseFor(r),sc=roundScore(r),d=derived(r);return `<div class="card"><div class="row"><div class="grow"><strong>${esc(c.name)}</strong><div class="tiny muted">${new Date(r.date).toLocaleDateString('nl-NL')} · ${r.holesCount} holes</div></div><div class="right"><strong>${sc.score}</strong><div class="tiny muted">${scoreLabel(sc.score,sc.par)}</div></div></div><div class="stat-row" style="margin-top:12px"><div class="stat"><strong>${d.fir}%</strong><span>FIR</span></div><div class="stat"><strong>${d.gir}%</strong><span>GIR</span></div><div class="stat"><strong>${d.putts}</strong><span>putts</span></div></div></div>`}).join('');return shell('Mijn spel',cards||'<div class="empty">Je afgeronde rondes komen hier te staan.</div>','HISTORIE')}
function renderModal(){if(state.modal.type==='new-round'){const selected=state.modal.courseId?state.courses.find(c=>c.id===state.modal.courseId):state.courses[0];return modal(`<h3>Nieuwe ronde</h3><div class="field"><label>Baan</label><select id="courseSelect">${state.courses.map(c=>`<option value="${c.id}" ${c.id===selected.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Tee</label><select id="teeSelect">${selected.tees.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('')}</select></div><div class="field"><label>Aantal holes</label><div class="pill-row"><button class="pill ${(state.modal.holes||9)===Math.min(9,selected.pars.length)?'active':''}" data-holes="${Math.min(9,selected.pars.length)}">${Math.min(9,selected.pars.length)}</button>${selected.pars.length>=18?`<button class="pill ${(state.modal.holes||9)===18?'active':''}" data-holes="18">18</button>`:''}</div></div><div class="field"><label>Handicap bij start (optioneel)</label><input id="hcpInput" inputmode="decimal" placeholder="bijv. 30,9"></div><button class="btn btn-primary" style="width:100%" data-action="confirm-round">Start ronde</button>`)}
 if(state.modal.type==='courses')return modal(`<h3>Baanbibliotheek</h3>${state.courses.map(courseCard).join('')}<button class="btn btn-secondary" style="width:100%" data-action="add-course">+ Baan handmatig toevoegen</button>`);
 if(state.modal.type==='details')return modal(`<h3>Extra slagdetails</h3><div class="field"><label>Afstand (optioneel)</label><input id="distanceInput" type="number" inputmode="numeric" value="${shotDraft.distance||''}" placeholder="meters"></div><p class="muted tiny">Later voegen we hier ligging, balvlucht, wind en notities aan toe. De snelle flow blijft altijd bovenaan staan.</p><button class="btn btn-primary" style="width:100%" data-action="save-details">Bewaren</button>`);
 if(state.modal.type==='finish')return modal(`<h3>Ronde afronden?</h3><p class="muted">Je kunt hem daarna terugzien bij Mijn spel en Analyse.</p><div class="grid2"><button class="btn btn-ghost" data-action="close-modal">Nog niet</button><button class="btn btn-primary" data-action="finish-round">Afronden</button></div>`);
 if(state.modal.type==='add-course')return modal(`<h3>Baan toevoegen</h3><div class="field"><label>Naam</label><input id="newCourseName"></div><div class="field"><label>Plaats</label><input id="newCourseLocation"></div><div class="field"><label>Holes</label><select id="newCourseHoles"><option value="9">9</option><option value="18">18</option></select></div><button class="btn btn-primary" style="width:100%" data-action="save-course">Toevoegen</button>`);
 return ''}
function modal(inner){return `<div class="modal-backdrop" data-backdrop><div class="modal"><div class="modal-handle"></div>${inner}</div></div>`}
function render(){if(golfMap){try{golfMap.remove()}catch{}golfMap=null}const app=document.getElementById('app');app.innerHTML=state.tab==='home'?home():state.tab==='round'?roundPage():state.tab==='analysis'?analysis():state.tab==='clubs'?clubsPage():gamePage();bind();if(state.tab==='round'&&activeRound())setTimeout(initRoundMap,0)}
function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;state.modal=null;render()});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=e=>handle(b.dataset.action,b));document.querySelectorAll('[data-club]').forEach(b=>b.onclick=()=>{shotDraft.club=b.dataset.club;render()});document.querySelectorAll('[data-result]').forEach(b=>b.onclick=()=>{shotDraft.result=b.dataset.result;render()});document.querySelectorAll('[data-hole]').forEach(b=>b.onclick=()=>{const r=activeRound();r.currentHole=Number(b.dataset.hole);save();shotDraft={club:null,result:null,distance:''};render()});document.querySelectorAll('[data-delete-shot]').forEach(b=>b.onclick=()=>{const r=activeRound();r.shots=r.shots.filter(s=>s.id!==b.dataset.deleteShot);resequ(r);save();render()});const cs=document.getElementById('courseSelect');if(cs)cs.onchange=()=>{state.modal.courseId=cs.value;const c=state.courses.find(x=>x.id===cs.value);state.modal.holes=Math.min(state.modal.holes||9,c.pars.length);render()};document.querySelectorAll('[data-holes]').forEach(b=>b.onclick=()=>{state.modal.holes=Number(b.dataset.holes);document.querySelectorAll('[data-holes]').forEach(x=>x.classList.toggle('active',x===b))});const bd=document.querySelector('[data-backdrop]');if(bd)bd.onclick=e=>{if(e.target===bd){state.modal=null;render()}}}
function resequ(r){for(let h=1;h<=r.holesCount;h++)getHoleShots(r,h).forEach((s,i)=>s.seq=i+1)}
function handle(a,b){if(a==='new-round'){state.modal={type:'new-round',courseId:state.courses[0].id,holes:9};render()}else if(a==='courses'){state.modal={type:'courses'};render()}else if(a==='pick-course'){state.modal={type:'new-round',courseId:b.dataset.id,holes:9};render()}else if(a==='close-modal'){state.modal=null;render()}else if(a==='confirm-round'){const courseId=document.getElementById('courseSelect').value,course=state.courses.find(c=>c.id===courseId),teeId=document.getElementById('teeSelect').value,holes=Math.min(state.modal.holes||9,course.pars.length),hcp=document.getElementById('hcpInput').value;const r={id:uid(),courseId,teeId,date:new Date().toISOString(),holesCount:holes,startingHandicap:hcp,currentHole:1,shots:[],completed:false};state.rounds.push(r);state.activeRoundId=r.id;state.tab='round';state.modal=null;save();render();toast('Ronde gestart')}else if(a==='save-shot'){const r=activeRound();if(!shotDraft.club||!shotDraft.result)return;const shots=getHoleShots(r,r.currentHole),penalty=shotDraft.result==='Penalty'?1:0,point=gpsPoint();if(point&&shots.length){const prev=shots.at(-1);if(prev.gps&&!prev.distance){const m=haversineMeters(prev.gps,point);if(m&&m<700){prev.distance=m;prev.distanceAuto=true}}}r.shots.push({id:uid(),hole:r.currentHole,seq:shots.length+1,club:shotDraft.club,result:shotDraft.result,distance:shotDraft.distance?Number(shotDraft.distance):null,distanceAuto:false,gps:point,penalty,createdAt:new Date().toISOString()});shotDraft={club:null,result:null,distance:''};save();render();toast(point?'Slag + GPS opgeslagen':'Slag opgeslagen')}else if(a==='details'){state.modal={type:'details'};render()}else if(a==='save-details'){shotDraft.distance=document.getElementById('distanceInput').value;state.modal=null;render()}else if(a==='prev-hole'){const r=activeRound();r.currentHole=Math.max(1,r.currentHole-1);save();render()}else if(a==='next-hole'){const r=activeRound();if(r.currentHole>=r.holesCount){state.modal={type:'finish'};render()}else{r.currentHole++;shotDraft={club:null,result:null,distance:''};save();render()}}else if(a==='finish-round'){const r=activeRound();r.completed=true;state.activeRoundId=null;state.modal=null;state.tab='game';save();render();toast('Ronde afgerond')}else if(a==='add-course'){state.modal={type:'add-course'};render()}else if(a==='save-course'){const name=document.getElementById('newCourseName').value.trim(),location=document.getElementById('newCourseLocation').value.trim(),n=Number(document.getElementById('newCourseHoles').value);if(!name)return;state.courses.push({id:uid(),name,location,favorite:false,tees:[{id:'standard',name:'Standaard',holes:Array(n).fill(0)}],pars:Array(n).fill(4)});save();state.modal={type:'courses'};render();toast('Baan toegevoegd')}else if(a==='toggle-gps'){gps.enabled?stopGPS():startGPS()}else if(a==='center-gps'){centerOnGPS()}else if(a==='edit-bag'){toast('Bag bewerken komt in de volgende stap')}}
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
render();
